apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ted-tls
  namespace: ted523-istio
spec:
  dnsNames:
  - nees.jorgeleandro.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: istio-tls
  duration: 8640h
  renewBefore: 7440h
